name: AttenST
channels:
  - pytorch
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip=20.3.3
  - python=3.8.5
  - pytorch=2.4.1
  - torchvision=0.12.0
  - pip:
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - backcall==0.2.0
      - click==8.1.8
      - compel==2.0.3
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.2.1
      - diffusers==0.32.2
      - docker-pycreds==0.4.0
      - dominate==2.9.1
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - executing==2.2.0
      - filelock==3.16.1
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - huggingface-hub==0.28.1
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.8
      - lightning-utilities==0.11.9
      - lpips==0.1.4
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mediapy==1.2.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - natsort==8.4.0
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.11.0.86
      - packaging==24.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.50
      - propcache==0.2.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.1.4
      - pyrallis==0.3.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.4.0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - safetensors==0.5.2
      - scikit-learn==1.3.2
      - scikit-video==1.1.11
      - scipy==1.10.1
      - sentry-sdk==2.22.0
      - setproctitle==1.3.4
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - torch==2.4.1
      - torchfile==0.1.0
      - torchmetrics==1.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - triton==3.0.0
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - utils==1.0.2
      - wandb==0.19.6
      - wcwidth==0.2.13
      - yarl==1.15.2
      - zipp==3.20.2
